language: python

matrix:
  include:
    - env: BROKER=sqlite
    - env: BROKER=mysql
      before_script:
        - mysql -u root -e 'CREATE DATABASE flask_celery_helper_test;'
        - mysql -u root -e 'GRANT ALL PRIVILEGES ON flask_celery_helper_test.* TO "user"@"localhost" IDENTIFIED BY "pass";'
    - env: BROKER=postgres
      before_script:
        - psql -U postgres -c 'CREATE DATABASE flask_celery_helper_test;'
        - psql -U postgres -c "CREATE USER user1 WITH PASSWORD 'pass';"
        - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE flask_celery_helper_test TO user1;'
    - env: BROKER=redis
      services: redis-server
    - env: BROKER=redis_sock,/tmp/redis.sock
      before_script: echo -e "daemonize yes\nunixsocket /tmp/redis.sock\nport 0" |redis-server -
    #- env: BROKER=mongo
    #- env: BROKER=couch
    #- env: BROKER=beanstalk
    #- env: BROKER=iron
    #- env: BROKER=rabbit

install:
  - pip install codecov tox

script:
  - tox
  - (cd ./tests && ls .coverage.py34 .coverage.py33 .coverage.pypy3 .coverage.pypy .coverage.py27 .coverage.py26)

after_success:
  - mv tests/.coverage* .
  - coverage combine
  - codecov
